[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.196"
serde_json = "1.0.113"
serde_derive = "1.0.193"
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
log = "0.4.20"
log4rs = { version = "1.2.0", features = ["json_encoder"] }
time = "0.3.34"
rand = "0.8.5"

[dev-dependencies]
axum-test = "14.3.0"
serde_yaml = "0.9.31"