[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.197"
serde_json = "1.0.116"
serde_derive = "1.0.193"
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
log = "0.4.21"
log4rs = { version = "1.3.0", features = ["json_encoder"] }
time = "0.3.36"
rand = "0.8.5"

[dev-dependencies]
axum-test = "14.8.0"
serde_yaml = "0.9.34"